version: 2.1
jobs:
  Testing:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run:
          name: "Setup Environment Variable"
          command: |
            echo "SAUCE_USERNAME=$SAUCE_USERNAME" > .env
            echo "SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY" >> .env
            echo "BUILD=v1.0.0" >> .env
            echo "BUILDNAME=Testing" >> .env
      - run:
          name: "Install Dependencies"
          command: npm install
      - run:
          name: "Running Test"
          command: npm run cloud
      - run:
          name: "Wrapping Test Result"
          command: "tar -cvf artifact.tar ./allure-report/"
      - store_artifacts:
          path: artifact.tar

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  Test-Workflow:
    jobs:
      - Testing
